CREATE TABLE foods (
    food_id SERIAL PRIMARY KEY,
    food_name TEXT NOT NULL,
    fdc_id INT,
    energy JSON NOT NULL,
    total_fats JSON NOT NULL,
    saturated_fats JSON,
    monosaturated_fats JSON,
    polysaturated_fats JSON,
    carbs_total JSON NOT NULL,
    fibre JSON,
    sugars JSON,
    protein JSON NOT NULL,
    cholesterol JSON,
    water JSON,
    calcium JSON,
    sodium JSON,
    potassium JSON,
    magnesium JSON,
    phosphorus JSON,
    iron JSON,
    zinc JSON,
    copper JSON,
    selenium JSON,
    vitamin_a_rae JSON,
    vitamin_a_retinol JSON,
    vitamin_a_carotene_alpha JSON,
    vitamin_a_carotene_beta JSON,
    cryptoxanthin_beta JSON,
    lycopene JSON,
    lutein_zeaxanthin_carotenoid JSON,
    thiamine_vitamin_b1 JSON,
    riboflavin_vitamin_b2 JSON,
    niacin_vitamin_b3 JSON,
    vitamin_b6 JSON,
    folate_vitamin_b9_Total JSON,
    folate_vitamin_b9_food JSON,
    folatevitamin_b9_dfe JSON,
    cobalamin_vitamin_b12 JSON,
    cobalamin_vitamin_b12_added JSON,
    ascorbic_acid_vitamin_c JSON,
    vitamin_d JSON,
    vitamin_e_added JSON,
    alpha_tocopherol_vitamin_e JSON,
    vitamin_k JSON,
    choline JSON,
    ethyl_alcohol JSON,
    caffeine JSON,
    theobromine JSON,
    publication_date TIMESTAMP,
    added_by TEXT,
    added_on TIMESTAMP
);